name: 'Remote Script Executor'
description: 'Execute a shell script on another Server'
branding:
  icon: 'airplay'  
  color: 'gray-dark'
inputs:
  server-address:
    description: 'Target Server Address'
    required: true
  script-name:
    description: 'Target Script name to execute'
    required: true
  password:
    description: 'Password to connect to the target server'
    required: true
runs:
  using: 'node16'
  main: 'index.js'