on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Test
        uses: ./
        with:
          server-address: ${{secrets.DEBUG_SERVER_ADDRESS}}
          script-name: myscript.sh
          password: ${{secrets.DEBUG_SERVER_PASSWORD}}